FROM ubuntu:26.04

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    ninja-build \
    git \
    pkg-config \
    curl \
    wget \
    zip \
    unzip

RUN apt-get install -y \
    libboost-graph-dev \
    libboost-program-options-dev \
    libvtk9-dev \
    nlohmann-json3-dev \
    libgtest-dev \
    libgmock-dev \
    libgmp-dev \
    libmpfr-dev

RUN apt-get install -y \
    libeigen3-dev \
    libcgal-dev

RUN apt-get install -y \
    clangd

RUN chown -R ubuntu:ubuntu /home/ubuntu

USER ubuntu
WORKDIR /home/ubuntu/dev
