name: "Build and test"

on:
  pull_request:
    branches:
      - main
      - dev
    
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
  
jobs:
  builds-and-tests:
    strategy:
      matrix:
        preset: [
          {"os": windows-latest, "name": "msbuild"},
          {"os": ubuntu-latest, "name": "gnu"}
        ]
        build-type: ["Debug", "Release"]
        
      fail-fast: false
        
    name: ${{ matrix.preset.os }} / ${{matrix.preset.name}} / ${{matrix.build-type}}
    runs-on: ${{ matrix.preset.os }}

    steps:
    - name: checkout repository
      uses: actions/checkout@v3

    - name: setup ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: getcmake
      uses: lukka/get-cmake@latest


    - name: Setup vcpkg 
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgJsonGlob: 'vcpkg.json'
 
    - name: Windows configure and build
      if: matrix.preset.name=='msbuild'
      run: |
        cmake --preset ${{matrix.preset.name}} -S . -B build
        cmake --build build --config ${{matrix.build-type}} -j

    - name: Windows Run tests
      if: matrix.preset.name=='msbuild'
      run: build/bin/${{matrix.build-type}}/tessellator_tests.exe

    - name: Ubuntu configure and build
      if: matrix.preset.name=='gnu'
      run: |
        cmake --preset ${{matrix.preset.name}} -S . -B build
        cmake --build build -j
        
    - name: Ubuntu Run tests
      if: matrix.preset.name=='gnu'
      run: build/bin/tessellator_tests

        
    