name: "Build and test"

on:
  push:
    branches:
      - main

env:
  WINDOWS_RELEASE_TAG: 2025-10-20-windows-x64-opensemba-tessellator
  LINUX_RELEASE_TAG: 2025-10-20-linux-opensemba-tessellator
  WINDOWS_FILENAME: opensemba-tessellator-windows-x64.tar.gz
  LINUX_FILENAME: opensemba-tessellator-linux.tar.gz

jobs:
  make-release:
    name: combine releases
    runs-on: ubuntu-latest
    # needs: build-temporary-releases

    steps:
    - name: download windows tar file
      uses: robinraju/release-downloader@v1
      with:
        repository: OpenSEMBA/tessellator
        tag: ${{env.WINDOWS_RELEASE_TAG}}
        fileName: ${{env.WINDOWS_FILENAME}}

    - name: download linux tar file
      uses: robinraju/release-downloader@v1
      with:
        repository: OpenSEMBA/tessellator
        tag: ${{env.LINUX_RELEASE_TAG}}
        fileName: ${{env.LINUX_FILENAME}}

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - name: Generating release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ steps.date.outputs.date }}-opensemba-tessellator"
        draft: True
        title: "${{matrix.preset.filename}} OpenSemba Tessellator release"
        files: |
          ${{env.WINDOWS_FILENAME}}
          ${{env.LINUX_FILENAME}}

    - name: Clean old pre-release
      uses: "sgpublic/delete-release-action@v1.2"
      with:
        pre-release-drop: true
        pre-release-keep-count: -1
        pre-release-drop-tag: true
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"